### ISSUE TITLE
Integration tests with Arrow nightly broken

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#152]
Traceback (from https://travis-ci.com/JDASoftwareGroup/kartothek/jobs/242929160)
```
Traceback (most recent call last):

  File "./ci/get_pyarrow_nightly.py", line 53, in <module>

    main()

  File "./ci/get_pyarrow_nightly.py", line 30, in main

    client_secret = os.environ["GITHUB_CLIENT_SECRET"]

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/os.py", line 669, in __getitem__

    raise KeyError(key) from None

KeyError: 'GITHUB_CLIENT_SECRET'

+ARROW_URL=

The command "./ci/before_install.sh" failed and exited with 1 during .
```

**Comment by lr4d** [comment]
These builds are erroring again:
```
++./ci/get_pyarrow_nightly.py

Traceback (most recent call last):

  File "./ci/get_pyarrow_nightly.py", line 53, in <module>

    main()

  File "./ci/get_pyarrow_nightly.py", line 46, in main

    raise RuntimeError("No nightly build found!")

RuntimeError: No nightly build found!

+ARROW_URL=

The command "./ci/before_install.sh" failed and exited with 1 during .
```
From https://travis-ci.com/JDASoftwareGroup/kartothek/jobs/245523119#L198
Seems like there are no wheels built atm for pyarrow 0.15 for python3, only bzip2-compressed tars
