### ISSUE TITLE
arrow nightlies CI jobs erroring

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#162]
These builds are erroring again:
```
++./ci/get_pyarrow_nightly.py

Traceback (most recent call last):

  File "./ci/get_pyarrow_nightly.py", line 53, in <module>

    main()

  File "./ci/get_pyarrow_nightly.py", line 46, in main

    raise RuntimeError("No nightly build found!")

RuntimeError: No nightly build found!

+ARROW_URL=

The command "./ci/before_install.sh" failed and exited with 1 during .
```
From https://travis-ci.com/JDASoftwareGroup/kartothek/jobs/245523119#L198
Seems like there are no wheels built atm for pyarrow 0.15 for python3, only bzip2-compressed tars

**Comment by crepererum** [comment]
## Background

arrow does not seem to produce wheels for Python 3 anymore. This is the current list of artifacts found upstream:

```
'pyarrow-0.15.0.dev103-cp27-cp27m-manylinux2010_x86_64.whl',
'pyarrow-0.15.0.dev105-cp27-cp27m-manylinux1_x86_64.whl',
'pyarrow-0.15.0.dev105-cp27-cp27m-manylinux2010_x86_64.whl',
'pyarrow-0.15.0.dev105-py27he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev105-py36he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev105-py37he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev110-cp27-cp27m-manylinux1_x86_64.whl',
'pyarrow-0.15.0.dev110-cp27-cp27m-manylinux2010_x86_64.whl',
'pyarrow-0.15.0.dev110-py27he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev110-py36he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev110-py37he1943e6_0.tar.bz2',
'pyarrow-0.15.0.dev116-cp27-cp27m-manylinux2010_x86_64.whl',
'pyarrow-0.15.0.dev116-py36he1943e6_0.tar.bz2',
```

So either we use conda for our whole setup or we use tools like [conda-press](https://github.com/regro/conda-press) to convert the conda builds to wheels.

**Comment by xhochy** [comment]
@crepererum `conda-press` is far from where it would be able to press Arrow. There have been a lot of nightly failures in the last days due to pytest updates, so hopefully the wheels will reappear the next days.

Otherwise, yes, using conda for the nightlies sounds fine, but don't upload the Arrow conda packages ATM (easy fix possibly).

**Comment by xhochy** [comment]
FYI: The failed build log for last night: https://travis-ci.org/ursa-labs/crossbow/builds/598529825 (didn't have a look yet)

**Comment by lr4d** [comment]
I'm seeing 
```
pyarrow-0.15.1-cp37-cp37m-macosx_10_6_intel.whl
pyarrow-0.15.1-cp27-cp27m-macosx_10_6_intel.whl
pyarrow-0.15.1-cp36-cp36m-win_amd64.whl
pyarrow-0.15.1-py36h8b68381_0.tar.bz2
pyarrow-0.15.1-cp36-cp36m-macosx_10_6_intel.whl
pyarrow-0.15.1-py37h8b68381_0.tar.bz2
pyarrow-0.15.1-py27h8b68381_0.tar.bz2
pyarrow-0.15.1-cp35-cp35m-manylinux2010_x86_64.whl
pyarrow-0.15.1-cp37-cp37m-manylinux1_x86_64.whl
pyarrow-0.15.1-cp36-cp36m-manylinux2010_x86_64.whl
pyarrow-0.15.1-py37he1943e6_0.tar.bz2
pyarrow-0.15.1-py27he1943e6_0.tar.bz2
pyarrow-0.15.1-cp27-cp27m-manylinux2010_x86_64.whl
pyarrow-0.15.1-py36he1943e6_0.tar.bz2
pyarrow-0.15.1-cp37-cp37m-win_amd64.whl
pyarrow-0.15.1-cp37-cp37m-manylinux2010_x86_64.whl
pyarrow-0.15.1-cp27-cp27m-manylinux1_x86_64.whl
pyarrow-0.15.1-cp35-cp35m-macosx_10_6_intel.whl
pyarrow-0.15.1-cp27-cp27mu-manylinux1_x86_64.whl
pyarrow-0.15.1-cp35-cp35m-win_amd64.whl
pyarrow-0.15.1-cp36-cp36m-manylinux1_x86_64.whl
```
atm. Note: no more `dev` after version number.
@xhochy do you happen to know if this format has changed recently?

**Comment by xhochy** [comment]
@lr4d 0.15.1 release candidate is in progress.
