### ISSUE TITLE
predicate parsing with OR broken

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#295]
### Problem description
See https://github.com/JDASoftwareGroup/kartothek/pull/294#issuecomment-638922148

However, after fixing the case for empty predicates on that development branch, the following bug shows up:
Reading datasets using somewhat complex predicates sometimes returns incorrect data.

### Example code (ideally copy-pastable)
```python

from tempfile import TemporaryDirectory
from storefact import get_store_from_url
from functools import partial

store_factory = partial(get_store_from_url, f"hfs://{TemporaryDirectory().name}")
dataset_uuid = "test"

import pandas as pd

df = pd.DataFrame({"A": range(10), "B": ["A", "B"] * 5, "C": range(-10, 0)})

from kartothek.io.eager import read_table, store_dataframes_as_dataset

dm = store_dataframes_as_dataset(
    store=store_factory, dataset_uuid=dataset_uuid, dfs=[df], partition_on=["A", "B"]
)

df1 = read_table(
    store=store_factory,
    dataset_uuid=dataset_uuid,
    predicates=[[("A", "<", 3)], [("A", ">", 5)], [("B", "==", "non-existent")]],
)
print(df1)

df2 = read_table(
    store=store_factory,
    dataset_uuid=dataset_uuid,
    predicates=[[("A", "<", 3)], [("A", ">", 5)]],
)

pd.testing.assert_frame_equal(df1, df2)
```
Output:
```
   A  B   C
0  0  A -10
1  1  B  -9
2  2  A  -8
3  3  B  -7
4  4  A  -6
5  5  B  -5
6  6  A  -4
7  7  B  -3
8  8  A  -2
9  9  B  -1
Traceback (most recent call last):
  File "/Users/xrzq/miniconda3/envs/sc-lastcalcs/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d6e03a9f4370>", line 31, in <module>
    pd.testing.assert_frame_equal(df1, df2)
  File "/Users/xrzq/miniconda3/envs/sc-lastcalcs/lib/python3.6/site-packages/pandas/_testing.py", line 1325, in assert_frame_equal
    obj, f"{obj} shape mismatch", f"{repr(left.shape)}", f"{repr(right.shape)}",
  File "/Users/xrzq/miniconda3/envs/sc-lastcalcs/lib/python3.6/site-packages/pandas/_testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame are different
DataFrame shape mismatch
[left]:  (10, 3)
[right]: (7, 3)
```
Note that `df1` contains values for `A` outside of the range defined by the predicates.

**Comment by SvoONs** [comment]
For which version do you encounter this behavior? For me the first read fails with `Value Error: Empty predicates` which seems like desired behavior.

**Comment by fjetter** [comment]
I also receive the `ValueError` message on
```
In [12]: pd.__version__
Out[12]: '0.24.2'

In [13]: import kartothek

In [14]: kartothek.__version__
Out[14]: '3.8.2'
```

Even though receiving an exception is better than receiving incorrect results, it is still not the correct behaviour since the query uses a valid predicate
