### ISSUE TITLE
Parquet `AssertionErrors` on long running jobs

### ISSUE THREAD

**Issue by NeroCorleone** [JDASoftwareGroup/kartothek#407]
### Problem description

We are seeing `AssertionErrrors` when creating a ktk dataset and it is unclear where these errors come from. 

### Example code (ideally copy-pastable)

Unfortunately not so easy: essentially we are triggering a long running (> 3h) ktk job with `kartothek.io.dask.dataframe.update_dataset_from_ddf`. During this long running job we sometimes (?) see the following stacktrace:

<details>

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/by/http_runner/run.py", line 170, in _call
    result = callable_(**params)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/adsapp.py", line 169, in do_full_load_job
    result = etl_job.process_full_load_job_recover()
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/jobs/transform_job.py", line 916, in process_full_load_job_recover
    result = strategy.process()
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/jobs/processing/YearlyProcessingStrategy.py", line 136, in process
    result = self.process_year(current_year=current_year)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/jobs/processing/MonthlyProcessingStrategy.py", line 135, in process_year
    current_year=current_year, current_month=current_month
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/jobs/processing/MonthlyProcessingStrategy.py", line 308, in process_month
    overwrite=(True if self.delta_time_range else False),
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/ads_http/jobs/transform_job.py", line 662, in compute
    result_metadata = etl_task.compute()
ads-dask
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/dask/utils.py", line 29, in apply
    return func(*args, **kwargs)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io/dask/dataframe_cube.py", line 306, in _unpack_list
    l = list(l)  # noqa
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/dask/bag/core.py", line 1964, in __next__
    return self.f(*vals)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/cube/query/_group.py", line 223, in load_group
    store=store,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/cube/query/_group.py", line 184, in _load_partition
    cube=cube, group=group, partition_mps=partition_mps, store=store
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/cube/query/_group.py", line 135, in _load_partition_dfs
    empty=empty,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/cube/query/_group.py", line 90, in _load_all_mps
    predicates=predicates,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 136, in _impl
    method_return = method(mp, *method_args, **method_kwargs)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 742, in load_dataframes
    date_as_object=dates_as_object,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/serialization/_generic.py", line 120, in restore_dataframe
    date_as_object=date_as_object,
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/serialization/_parquet.py", line 128, in restore_dataframe
    parquet_file, columns_to_io, predicates_for_pushdown
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/kartothek/serialization/_parquet.py", line 237, in _read_row_groups_into_tables
    row_group = parquet_file.read_row_group(row, columns=columns)
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/pyarrow/parquet.py", line 271, in read_row_group
    use_threads=use_threads)
  File "pyarrow/_parquet.pyx", line 1079, in pyarrow._parquet.ParquetReader.read_row_group
    return self.read_row_groups([i], column_indices, use_threads)
  File "pyarrow/_parquet.pyx", line 1098, in pyarrow._parquet.ParquetReader.read_row_groups
    check_status(self.reader.get()

  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
    raise IOError(message)
```
</details>

### Used versions
<details>
```
# pip freeze
ads-http==4.0.10.dev34+g14c235f
attrs==20.2.0
azure-common==1.1.25
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
blinker==1.4
bokeh==2.2.1
by.flask-stratosphere==1.5.2
by.http-runner==11.1.1
cee-syslog-handler==0.5.0
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
cloudpickle==1.5.0
contextvars==2.4
cryptography==3.2.1
cytoolz==0.10.1
dask==2.30.0
dataclasses==0.7
decorator==4.4.2
distributed==2.30.1+by.1
Flask==1.1.2
fsspec==0.8.4
gunicorn==20.0.4
HeapDict==1.0.1
idna==2.10
immutables==0.14
itsdangerous==1.1.0
Jinja2==2.11.2
kartothek==3.17.0
locket==0.2.0
lz4==3.1.0
MarkupSafe==1.1.1
milksnake==0.1.5
msgpack==1.0.0
numpy==1.19.1
packaging==20.4
pandas==1.1.4
pandas-interface==0.17.0
partd==1.1.0
Pillow==7.2.0
pip==19.2.3
prometheus-client==0.8.0
prompt-toolkit==3.0.5
psutil==5.7.3
pyarrow==1.0.1
pycparser==2.20
pydantic==1.7.2
pygelf==0.3.4
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
replenishment-interface==2.3.0
requests==2.24.0
retail-interface==0.21.0
sentry-sdk==0.16.2
setuptools==41.2.0
simplejson==3.17.2
simplekv==0.14.1
six==1.15.0
sortedcontainers==2.2.2
storefact==0.10.0
structlog==20.1.0
tblib==1.7.0
terminaltables==3.1.0
toolz==0.10.0
tornado==6.1
typing-extensions==3.7.4.3
uritools==3.0.0
urllib3==1.25.10
urlquote==1.1.4
voluptuous==0.11.7
wcwidth==0.2.5
Werkzeug==1.0.1
wheel==0.33.6
zict==2.0.0
zstandard==0.14.0
```
</details>

**Comment by fjetter** [comment]
Very likely caused by Looks like this is caused by https://github.com/Azure/azure-sdk-for-python/issues/16723
