### ISSUE TITLE
CI build fails with "ImportError: libthrift.so.0.14.1: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by steffen-schroeder-by** [JDASoftwareGroup/kartothek#481]
### Problem description
https://github.com/JDASoftwareGroup/kartothek/actions/runs/955426275

### Example code (ideally copy-pastable)

```python
Run python -c "import kartothek"
  python -c "import kartothek"
  python -c "import kartothek.api"
  python -c "import kartothek.api.consistency"
  python -c "import kartothek.api.cube"
  python -c "import kartothek.api.dataset"
  python -c "import kartothek.api.discover"
  python -c "import kartothek.api.serialization"
  python -c "import kartothek.cli"
  python -c "import kartothek.core"
  python -c "import kartothek.io"
  python -c "import kartothek.io_components"
  python -c "import kartothek.serialization"
  python -c "import kartothek.utils"
  shell: /usr/bin/bash -l {0}
  env:
    IS_MASTER_BUILD: false
    IS_TAG: false
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/kartothek/kartothek/kartothek/api/consistency.py", line 9, in <module>
    from kartothek.core.common_metadata import validate_shared_columns
  File "/home/runner/work/kartothek/kartothek/kartothek/core/__init__.py", line 1, in <module>
    from kartothek.core.common_metadata import *  # noqa: F401, F403
  File "/home/runner/work/kartothek/kartothek/kartothek/core/common_metadata.py", line 13, in <module>
    import pyarrow.parquet as pq
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyarrow/parquet.py", line 33, in <module>
    import pyarrow._parquet as _parquet
ImportError: libthrift.so.0.14.1: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.
```

### Used versions

<details>

```
# Paste your output of `pip freeze` or `conda list` here

```

</details>

**Comment by xhochy** [comment]
Should be fixed by now, this was an issue with an unexpected ABI breakage by libthrift.

**Comment by steffen-schroeder-by** [comment]
Thanks Uwe, I will close this issue and follow up the current CI breakge `AssertionError: Regex pattern 'Cannot store empty datasets' does not match 'No data left to save outside partition columns'.` in a seperate issue.
