### ISSUE TITLE
Using s3 to store datasets

### ISSUE THREAD

**Issue by josephwinston** [JDASoftwareGroup/kartothek#52]
I am using minio to server my s3 context.

The creation of the store is:

```
from storefact import get_store_from_url
store = get_store_from_url('s3://key:secret@internal:9000/kart?create_if_missing=true')
```

Then I use the following to write the df:

```
from kartothek.io.eager import store_dataframes_as_dataset
dm = store_dataframes_as_dataset(store,
                                                          'runRecordDescriptionTable',
                                                          df,
                                                          metadata_version=4)    
```

But the following error occurs:

```
Traceback (most recent call last):
  File "s3fsLoad.py", line 243, in <module>
    sys.exit(main() or 0)
  File "s3fsLoad.py", line 225, in main
    metadata_version=4)    
  File "</home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/decorator.py:decorator-gen-5>", line 2, in store_dataframes_as_dataset
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io_components/utils.py", line 207, in normalize_args
    return _wrapper(*args, **kwargs)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io_components/utils.py", line 205, in _wrapper
    return function(*args, **kwargs)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io/eager.py", line 478, in store_dataframes_as_dataset
    store=store, dataset_uuid=dataset_uuid, df_serializer=df_serializer
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 105, in _impl
    method_return = method(mp, *method_args, **method_kwargs)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 990, in store_dataframes
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 973, in store_dataframes
    file_dct[table] = df_serializer.store(store, key, df)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/kartothek/serialization/_parquet.py", line 199, in store
    store.put(key, buf.getvalue().to_pybytes())
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/simplekv/__init__.py", line 147, in put
    self._check_valid_key(key)
  File "/home/josephwinston/anaconda3/envs/kartothek/lib/python3.6/site-packages/simplekv/__init__.py", line 192, in _check_valid_key
    raise ValueError('%r contains illegal characters' % key)
ValueError: 'runRecordDescriptionTable/table/1d2e32e172f949d4a90d6e727ea0829e.parquet' contains illegal characters

```
It appears that the problem is the s3 bucket name is `runRecordDescriptionTable/table/1d2e32e172f949d4a90d6e727ea0829e.parquet'`

Is there a transform that I need to make to ensure the bucket name is correct?

**Comment by xhochy** [comment]
@josephwinston To use `/` in `simplekv` keys you need the `h`-prefixed stores in `storefact`. The following should make this work for you:

```
from storefact import get_store_from_url
store = get_store_from_url('hs3://key:secret@internal:9000/kart?create_if_missing=true')
```

**Comment by josephwinston** [comment]
Thank you
