### ISSUE TITLE
`eager.store_dataframes_as_dataset` input is not satisfying `parse_input_to_metapartition` docstring specification

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#63]
Summary:
- `{"data":{"table1": df, "table2": df3}}` is an invalid input to `store_dataframes_as_dataset` (it should be valid)
- `{"table1": df, "table2": df3}` is valid input to  `store_dataframes_as_dataset` (but this format is not specified as such in docsring)

`parse_input_to_metapartition` docstring extract:
```
  1. Mode - Dictionary with partition information
        In this case, a dictionary is supplied where the keys describe the partition.
            * **label** - (optional) Unique partition label. If None is given, a UUID \
                        is generated using :func:`kartothek.core.uuid.gen_uuid`.
            * **data** - A dict or list of tuples. The keys represent the table name \
                        and the values are the actual payload data as a pandas.DataFrame.
            * **indices** - Deprecated, see the keyword argument `secondary_indices` to create indices.
                            A dictionary to describe the dataset indices. All \
                            partition level indices are finally merged using \
                            :func:`kartothek.io_components.metapartition.MetaPartition.merge_indices` \
                            into a single dataset index

```

Example (in quotes are debugging comments):
```
from kartothek.io.eager import store_dataframes_as_dataset
import numpy as np
import pandas as pd
from functools import  partial
from storefact import get_store_from_url

from tempfile import TemporaryDirectory

dataset_dir = TemporaryDirectory()
store_factory = partial(get_store_from_url, f"hfs://{dataset_dir.name}")

df = pd.DataFrame({"B": [pd.Timestamp("2019")]})

df3 = pd.DataFrame(
    {
        "B": pd.to_datetime(["20130102", "20190101"]),
        "L": [1, 4],
        "Q": [True, False],
    }
)
df3.dtypes
store_dataframes_as_dataset(
    store=store_factory,
    dataset_uuid="multiple_partitioned_tables",
    dfs={"data":{"table1": df, "table2": df3}},
    partition_on='B',
)
"""
`obj` in `parse_input_to_metapartition` is
    {'data': [('data', {'table1':            B
    0 2019-01-01, 'table2':            B  L      Q
    0 2013-01-02  1   True
    1 2019-01-01  4  False})]}
"""

store_dataframes_as_dataset(
    store=store_factory,
    dataset_uuid="multiple_partitioned_tables",
    dfs={"table1": df, "table2": df3},
    partition_on='B',
)
"""
`obj` in `parse_input_to_metapartition` is
    {'data': [('table1',            B
    0 2019-01-01), ('table2',            B  L      Q
    0 2013-01-02  1   True
    1 2019-01-01  4  False)]}
"""

```

**Comment by lr4d** [comment]
Sorry for the complex example, below is a MWE (on master branch):
```
from functools import partial
from tempfile import TemporaryDirectory

import pandas as pd
from storefact import get_store_from_url

from kartothek.io.eager import store_dataframes_as_dataset

dataset_dir = TemporaryDirectory()
store_factory = partial(get_store_from_url, f"hfs://{dataset_dir.name}")

df = pd.DataFrame({"B": [pd.Timestamp("2019")]})
store_dataframes_as_dataset(
    store=store_factory, dataset_uuid="uuid", dfs={"data": {"table1": df}}
)
```
Error:
```
Traceback (most recent call last):
  File "/Users/xrzq/miniconda3/envs/kartothek/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-16183ef534cd>", line 13, in <module>
    dfs={"data":{"table1": df}},
  File "</Users/xrzq/miniconda3/envs/kartothek/lib/python3.7/site-packages/decorator.py:decorator-gen-122>", line 2, in store_dataframes_as_dataset
  File "/Users/xrzq/public_workspace/kartothek/kartothek/io_components/utils.py", line 209, in normalize_args
    return _wrapper(*args, **kwargs)
  File "/Users/xrzq/public_workspace/kartothek/kartothek/io_components/utils.py", line 207, in _wrapper
    return function(*args, **kwargs)
  File "/Users/xrzq/public_workspace/kartothek/kartothek/io/eager.py", line 479, in store_dataframes_as_dataset
    mp = parse_input_to_metapartition(dfs, metadata_version)
  File "/Users/xrzq/public_workspace/kartothek/kartothek/io_components/metapartition.py", line 1615, in parse_input_to_metapartition
    metadata_version=metadata_version,
  File "/Users/xrzq/public_workspace/kartothek/kartothek/io_components/metapartition.py", line 217, in __init__
    partition_keys=partition_keys,
  File "/Users/xrzq/public_workspace/kartothek/kartothek/core/common_metadata.py", line 271, in make_meta
    raise ValueError("Input must be a pyarrow schema, or a pandas dataframe")
ValueError: Input must be a pyarrow schema, or a pandas dataframe
```
Swapping the `dfs` argument for `dfs={"data": [("table1", df)]}` results in the same error.

**Comment by fjetter** [comment]
The issue is about `store_dataframes_as_dataset` and not about `parse_input_to_metapartition` is it?

**Comment by lr4d** [comment]
I checked, yes it is caused by `store_dataframes_as_dataset`

**Comment by SvoONs** [comment]
I could take this one up. Just to clarify: the accepted input formats for `dfs` in reference to the provided MWE should be `{"data": {"table1": df}}`, `{"table1": df}` and `{"data": [("table1", df)]}`?

**Comment by lr4d** [comment]
According to the `parse_input_to_metapartition` docstring, `{"table1": df}` is not supported. But since user-provided labels and indices are both deprecated, that should be the way to pass it in the future.

**Comment by lr4d** [comment]
So, actually responding to your question. Atm, I think ideally we should support both `{"data": {"table1": df}}` and `{"table1": df}`, as well as the equivalent list of tuples combinations `{"data": [("table1", df)]}` and `[("table1", df)]`
