### ISSUE TITLE
Kartothek attempts to use simplekv incorrectly

### ISSUE THREAD

**Issue by peterdolan** [JDASoftwareGroup/kartothek#69]
System: OSX
Python version: 3.6.7
Kartothek version: 3.0.0
simplekv version: 0.12.0

The following code (which is a fairly minimal example) is giving me issues: 

```
import pandas as pd
from kartothek.io.eager import store_dataframes_as_dataset
from simplekv.fs import FilesystemStore

store = FilesystemStore('./data')

df = pd.DataFrame(
    {
        "A": [1,2,3],
        "B": [1,2,3],
    }
)
dm = store_dataframes_as_dataset(store, "peter_df", df, metadata_version=4)
```

Kartothek tries to write to simplekv with the key `peter_df/table/76db5d03cb294fbb913544d70d3ec353.parquet`. As far as I can tell, simplekv does not accept `/` as a character in its key name, so this fails.

Below is a detiailed traceback of the error:

```
Writing dataframe failed.
'peter_df/table/9131c25517fb4baabd1a9e4827f65fca.parquet' contains illegal characters
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
A    3 non-null int64
B    3 non-null int64
dtypes: int64(2)
memory usage: 128.0 bytes

   A  B
0  1  1
1  2  2
2  3  3
Traceback (most recent call last):
  File "k_exp.py", line 13, in <module>
    dm = store_dataframes_as_dataset(store, "peter_df", df, metadata_version=4)
  File "<decorator-gen-5>", line 2, in store_dataframes_as_dataset
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io_components/utils.py", line 207, in normalize_args
    return _wrapper(*args, **kwargs)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io_components/utils.py", line 205, in _wrapper
    return function(*args, **kwargs)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io/eager.py", line 478, in store_dataframes_as_dataset
    store=store, dataset_uuid=dataset_uuid, df_serializer=df_serializer
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 105, in _impl
    method_return = method(mp, *method_args, **method_kwargs)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 990, in store_dataframes
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/io_components/metapartition.py", line 973, in store_dataframes
    file_dct[table] = df_serializer.store(store, key, df)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/kartothek/serialization/_parquet.py", line 199, in store
    store.put(key, buf.getvalue().to_pybytes())
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/simplekv/__init__.py", line 147, in put
    self._check_valid_key(key)
  File "/anaconda3/envs/exp/lib/python3.6/site-packages/simplekv/__init__.py", line 192, in _check_valid_key
    raise ValueError('%r contains illegal characters' % key)
ValueError: 'peter_df/table/9131c25517fb4baabd1a9e4827f65fca.parquet' contains illegal characters
```

**Comment by crepererum** [comment]
We require the store to implement [ExtendedKeyspaceMixin](https://github.com/mbr/simplekv/blob/00500e2d26528b5d4cfdfc9611651d0cab011164/simplekv/contrib/__init__.py#L16]. The easiest way to archive that is to use [storefact](https://github.com/blue-yonder/storefact) and the store types that start with an `h`. You may also want to have a look at #62 which should make it easier for new users to get started. We could probably verify that the stores are either implement `ExtendedKeyspaceMixin` or a [store decorators](https://github.com/mbr/simplekv/blob/00500e2d26528b5d4cfdfc9611651d0cab011164/simplekv/decorator.py#L6).
